const CONFIG={names:"Nama Kamu & Nama Pasangan",startDate:"2024-08-17T00:00:00",startDateText:"17 Agustus 2024",heroImage:"assets/images/hero.jpg",heroMessage:"Satu cerita, dua hati, dan banyak kenangan yang ingin terus kita simpan.",quote:"Kalau boleh memilih lagi, aku tetap akan memilih kamu.",intro:"Terima kasih sudah menjadi rumah di hari-hari yang melelahkan, menjadi alasan untuk tersenyum, dan menjadi bagian paling indah dari perjalanan ini.",signature:"Dengan cinta, Nama Kamu ♥",letter:`Hai, sayang.

Hari ini kita kembali sampai di satu tanggal yang spesial. Aku cuma ingin bilang terima kasih. Terima kasih karena sudah bertahan, sudah mendengarkan, sudah memahami, dan sudah menjadi seseorang yang selalu ingin aku temui di akhir hari.

Aku tahu hubungan kita tidak selalu sempurna. Ada hari ketika kita tertawa sampai lupa waktu, ada juga hari ketika kita harus belajar memahami satu sama lain. Tapi dari semua itu, aku semakin yakin bahwa aku ingin terus berjalan bersamamu.

Semoga cerita kita tidak berhenti di anniversary ini. Semoga masih ada banyak ulang tahun, banyak perjalanan, banyak foto, banyak pelukan, dan banyak alasan untuk berkata: “untung aku bertemu kamu.”

Happy Anniversary, sayang. Aku sayang kamu, hari ini, besok, dan seterusnya.`,finalMessage:"Semoga setelah hari ini masih ada ribuan hari lain yang bisa kita rayakan bersama."};
const TIMELINE=[["17 AGUSTUS 2024","Awal Cerita","Hari ketika semuanya dimulai. Mungkin sederhana, tapi ternyata menjadi awal dari sesuatu yang sangat berarti."],["28 AGUSTUS 2024","Mulai Dekat","Obrolan yang awalnya biasa berubah menjadi bagian favorit dari setiap hari."],["15 SEPTEMBER 2024","First Date","Satu tempat, dua orang, dan satu kenangan yang sampai sekarang masih sering kita ceritakan."],["17 NOVEMBER 2024","Bertahan Bersama","Kita belajar bahwa cinta bukan hanya tentang bahagia, tapi juga tentang saling memilih ketika keadaan tidak mudah."],["17 AGUSTUS 2025","Anniversary Pertama","Satu tahun. Banyak cerita, banyak tawa, dan semakin banyak alasan untuk bersyukur."],["HARI INI","Our Next Chapter","Dan sekarang, kita di sini. Masih bersama, masih belajar, dan masih punya banyak cerita untuk ditulis."]];
const GALLERY=[["assets/images/photo1.jpg","Our favorite day"],["assets/images/photo2.jpg","Just us"],["assets/images/photo3.jpg","A little adventure"],["assets/images/photo4.jpg","Your smile"],["assets/images/photo5.jpg","Forever memory"]];
const REASONS=[["♥","Senyummu","Karena satu senyummu sering kali cukup untuk membuat hariku jauh lebih baik."],["☀","Caramu peduli","Kamu memperhatikan hal-hal kecil yang bahkan sering tidak aku sadari."],["✦","Kamu apa adanya","Aku suka versi kamu yang tidak perlu berpura-pura menjadi siapa-siapa."],["♡","Caramu mendengarkan","Terima kasih karena selalu memberi ruang untuk ceritaku."],["∞","Kesabaranmu","Kita sama-sama belajar, dan kamu selalu mengingatkanku untuk tidak menyerah."],["✿","Kehadiranmu","Pada akhirnya, hal sederhana seperti kamu ada di sini sudah cukup."]];
const FAVORITES=[["☕","Tempat date","Kafe kecil dengan obrolan panjang."],["🎵","Lagu kita","Pilih lagu yang selalu mengingatkan kalian satu sama lain."],["🍜","Makanan favorit","Makanan yang selalu terasa lebih enak kalau dimakan berdua."],["📍","Tempat spesial","Tempat pertama yang menyimpan kenangan penting."],["📷","Foto favorit","Satu foto yang tidak pernah bosan dilihat."],["🌙","Waktu favorit","Malam panjang dengan cerita yang tidak ada habisnya."]];
const BUCKET=["Sunset date di pantai","Traveling ke kota yang belum pernah kita kunjungi","Bikin album foto fisik","Nonton konser bareng","Masak dinner bersama","Mencoba 10 tempat makan baru","Road trip tanpa itinerary","Merayakan anniversary berikutnya dengan cara yang lebih spesial"];

document.addEventListener("DOMContentLoaded",()=>{heroNames.textContent=CONFIG.names;heroMessage.textContent=CONFIG.heroMessage;quoteText.textContent=CONFIG.quote;introText.textContent=CONFIG.intro;letterText.textContent=CONFIG.letter;signature.textContent=CONFIG.signature;finalMessage.textContent=CONFIG.finalMessage;heroImage.src=CONFIG.heroImage;startDateText.textContent=CONFIG.startDateText;renderTimeline();renderGallery();renderReasons();renderFavorites();renderBucket();setupReveal();setupLightbox();setupMusic();createHearts();setTimeout(()=>loader.style.display="none",900);updateCounter();setInterval(updateCounter,1000)});
function renderTimeline(){timeline.innerHTML=TIMELINE.map(x=>`<article class="event reveal"><div class="date">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join("")}
function renderGallery(){galleryGrid.innerHTML=GALLERY.map(x=>`<div class="gallery-item reveal" data-img="${x[0]}"><img src="${x[0]}" alt="${x[1]}" loading="lazy"></div>`).join("")}
function renderReasons(){reasonGrid.innerHTML=REASONS.map(x=>`<article class="reason reveal"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join("")}
function renderFavorites(){favoriteGrid.innerHTML=FAVORITES.map(x=>`<article class="favorite reveal"><span class="icon">${x[0]}</span><div><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join("")}
function renderBucket(){bucketList.innerHTML=BUCKET.map((x,i)=>`<div class="bucket-item reveal"><span>${x}</span><span>${String(i+1).padStart(2,"0")}</span></div>`).join("")}
function updateCounter(){const diff=Math.max(0,Date.now()-new Date(CONFIG.startDate).getTime());days.textContent=Math.floor(diff/86400000).toLocaleString("id-ID");hours.textContent=Math.floor(diff/3600000)%24;minutes.textContent=Math.floor(diff/60000)%60;seconds.textContent=Math.floor(diff/1000)%60}
function setupReveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});document.querySelectorAll(".reveal").forEach(e=>io.observe(e))}
function setupLightbox(){const box=lightbox,img=lightboxImg;document.querySelectorAll(".gallery-item").forEach(el=>el.onclick=()=>{img.src=el.dataset.img;box.classList.add("show")});closeLightbox.onclick=()=>box.classList.remove("show");box.onclick=e=>{if(e.target===box)box.classList.remove("show")}}
function setupMusic(){const audio=bgMusic;musicBtn.onclick=async()=>{if(audio.paused){try{await audio.play();musicBtn.innerHTML="♫ <span>Pause</span>"}catch(e){alert("Tambahkan file assets/audio/music.mp3 terlebih dahulu.")}}else{audio.pause();musicBtn.innerHTML="♫ <span>Music</span>"}};replayBtn.onclick=()=>scrollTo({top:0,behavior:"smooth"})}
function createHearts(){setInterval(()=>{const h=document.createElement("span");h.className="heart-particle";h.textContent=Math.random()>.3?"♥":"♡";h.style.left=Math.random()*100+"%";h.style.fontSize=8+Math.random()*14+"px";h.style.animationDuration=5+Math.random()*6+"s";hearts.appendChild(h);setTimeout(()=>h.remove(),12000)},900)}
